export const LIVE = "@";
export const REST = "#";
export const FLOOR = "-";
export const SIDE_WALL = "|";
export const EMPTY = ".";
export const PREVIEW = " ";
export const MAX_CHAMBER_HEIGHT = 25;
export const NUM_OF_COLS = 17;
export const GRAVITY_SPEED = 250; //ms
export const PREVIEW_COLS = 5;
export const TOTAL_NUM_OF_COLS = NUM_OF_COLS + PREVIEW_COLS;
